title: Vaddadi Lalithanjali
logo: /assets/img/logo.png
description: I am a Data Scientist and Java Developer having one year of experience.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
